name: AutoMinecart
main: com.gmail.uprial.autominecart.AutoMinecart
version: 0.1.2
api-version: 1.20
commands:
   autominecart:
      description: Reload AutoMinecart config
      usage: /autominecart help
      permission:
      permission-message:
permissions:
  autominecart.reload:
        description: Gives access to AutoMinecart 'reload' command
        default: op
